---
title: doingbird
timezone: Australia/Sydney
collections:
  category:
    title: Category
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/:title/"
    author:
    Main Image: "/assets/placeholder.png"
    Credits Text: ''
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: category
  values:
    layout: category
description: magazine
permalink: pretty
Masthead Color: black
